### ISSUE TITLE
Types?

### ISSUE THREAD

**Issue by kashw2** [alepiumetti/chakra-ui-table-w-pagination-sort-search#10]
Hi, are there any plans to add TypeScript support to this project or would you be open to accepting contributions that do?

My team is currently using this in a project of ours that uses TypeScript and having to either include a declarations.d.ts that manually exports a ES module or use `// @ts-ignore` whenever we import the module is just a bit of a nitpick that we have. None the less it doesn't slow down our velocity and we'd be able to manage without.

Thanks!

**Comment by alepiumetti** [comment]
For the moment, there is no plan to add Types. 
Currently, I don't have sufficient expertise in TypeScript to add the types in an optimal way. However, the project is open to new contributions, so feel free to open a PR. 

Thanks for your interest! 🙌

**Comment by alepiumetti** [comment]
I am closing the issue as 'resolved'. We will follow up on it in a potential PR.

Thanks again.
