### ISSUE TITLE
Overrides Chakra theme

### ISSUE THREAD

**Issue by FilipBPaven** [alepiumetti/chakra-ui-table-w-pagination-sort-search#9]
Hello,

Facing a problem when the:
```

	<PaginationTable
                    pageSize={pageSize}
                    setPageSize={setPageSize}
                    pageIndex={pageIndex}
                    setPageIndex={setPageIndex}				
                    totalItemsCount={filteredRows.length}
                    pageSizeOptions={[10, 25, 50]}
                />
```

is overriding my chakra 

```
const theme = extendTheme({
	styles: {
		global: {
			body: {
				bg: "#090A0B",
				color: "white",
			},
		},
	},
});
```

The body turns white. Do you know why? Can we disable it making changes to the theme?

**Comment by alepiumetti** [comment]
Hi! Thank for create an issue. 

I think this problem is because the component has their own provider. I'll test your case and then I will find a solution. 
If you need a fix, feel free to make a PR. :)

**Comment by alepiumetti** [comment]
This issue was closed in https://github.com/alepiumetti/chakra-ui-table-w-pagination-sort-search/commit/c84488079cfb897ae47fe42f03a950f18a4cfe05 
Upgrade this module and should work your theme.
